version: "3.8"

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ID=node1
      - BATTLE_SCORE=23
      - PORT=8000
      - PEERS=localhost:8001,localhost:8002,localhost:8003,localhost:8004

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - NODE_ID=node2
      - BATTLE_SCORE=17
      - PORT=8001
      - PEERS=localhost:8000,localhost:8002,localhost:8003,localhost:8004

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - NODE_ID=node3
      - BATTLE_SCORE=35
      - PORT=8002
      - PEERS=localhost:8000,localhost:8001,localhost:8003,localhost:8004

  node4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - NODE_ID=node4
      - BATTLE_SCORE=29
      - PORT=8003
      - PEERS=localhost:8000,localhost:8001,localhost:8002,localhost:8004

  node5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    environment:
      - NODE_ID=node5
      - BATTLE_SCORE=19
      - PORT=8004
      - PEERS=localhost:8000,localhost:8001,localhost:8002,localhost:8003
